* Film alimentaire réutilisable

** Tissu et cire d'abeille

*** ingrédients

- Un morceau de tissu, de préférence pas trop épais. Coupez un morceau de tissu
  de la taille de votre choix. Une fois que votre tissu est lavé, vous pouvez le
  repasser. Attention, comme le tissu sera mis dans le four, ne coupez des
  morceaux trop gros.
- De la cire d’abeille. Vous trouverez facilement de la cire d’abeille chez des
  producteurs, dans les magasins bio ou sur le net. Posez votre morceau de tissu
  sur la plaque du four et saupoudrez le avec la cire d’abeille.

*** recette

- Préchauffez le four à 80°C et enfournez environ 5min.
- Une fois que la cire est fondue et que le tissu est bien imprégné partout,
  sortez le et étendez le pour le laisser refroidir jusqu’à ce que la cire soit
  bien dure.

*** notes

Rincer et sécher après chaque utilisation.


*** source

https://toitsalternatifs.fr/conseils-pratiques/zero-dechet-remplacer-le-film-plastique-etirable-par-un-film-alimentaire-lavable/
